CREATE USER HR IDENTIFIED BY hrpass;
ALTER USER HR DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER HR TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO HR;
GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE TO HR;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE, UNLIMITED TABLESPACE TO HR;